version: "3"

services:
  ai-student-advisor-frontend:
    image: ai-student-advisor/frontend
    build: .
    container_name: ai-student-advisor-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - ai-student-advisor-default

networks:
  ai-student-advisor-default:
